### ISSUE TITLE
not able to yield a coroutine from rust 

### ISSUE THREAD

**Issue by surajprak** [amethyst/rlua#121]
RuntimeError("attempt to yield across a C-call boundary\nstack traceback:\n\t[C]: in ?\n\t[C]: in function \'coroutine.yield\'\n\t[string \"?\"]:1

I am trying below
```
let http =
            lua_ctx.create_function(|ctx, (a, b, c, d, e):(String, String, String, HashMap<String, String>, String)| {
                debug!("***************Inside http_call_rlua**********************");

                let res = http_call_rlua(a, b, c, d, e);
                   Err(err) => {
  let address: String = ctx.load("coroutine.yield(123)").eval::<String>().unwrap();
                     Ok(address)
                   },
                  Ok(result) =>{
                      Ok(result)
                  },
                }
            }).unwrap();
        globals.set("http_call_rlua", http).unwrap();
             
```

**Comment by kyren** [comment]
You can't yield across C call boundaries.  in the Lua C API, what you want to do would be accomplished using `lua_yieldk`, where you would provide a continuation function as the final parameter, but rlua doesn't expose this ability yet (I mentioned this in a previous issue).  It is not as simple as just wrapping `lua_yieldk`, `lua_yieldk` *longjmps* in order to yield, so I need to invent a different API to do the same thing safely.

In either case, you won't be able to yield transparently like that at all until generators are stabilized and rlua somehow integrates with them to provide `lua_yieldk` like functionality.

In the meantime, instead of waiting for *some* kind of API to emulate the behavior of `lua_yieldk`, you're going to have to yield from the Lua that *called* your callback.

Just so you understand that it's not magically easy in the C API either, this is how you do it in C: https://www.lua.org/manual/5.3/manual.html#4.7

**Comment by surajpayu** [comment]
thanks for your response. I will do it in lua. I need your help on below issue. I want to create a mechanism to create lua wrapper on top of function defined in rust and exposed to lua
for e.g.
```
let add =
            lua_ctx.create_function(|ctx, (a, b):(i32, i32)| {
                debug!("***************Inside add**********************");
                Ok(add(a,b))
            }).unwrap();
        globals.set("add", add).unwrap();
```

In lua i want a wrapper fn
function add_wrapper(a, b){
     res, err =add()
     if err ==  "NotReady" then
         res = coroutine.yield()
     end
     return res
}


I want to generate this add_wrapper function dynamically. By this i mean that if there are other functions similar to add, i would be able to generate wrapper function dynamically without writing separate code for each wrapper function in lua every time.

**Comment by kyren** [comment]
> I want to generate this add_wrapper function dynamically. By this i mean that if there are other functions similar to add, i would be able to generate wrapper function dynamically without writing separate code for each wrapper function in lua every time.

I'm pretty sure this is achievable, you could even do the wrapping itself in Rust (again, *via* Lua).  The following code is completely untested:

```lua
function wrap_ready(f)
    return function(...)
        local res, err = f(...)
        if err = "NotReady" then
            res = coroutine.yield()
        end
        return res
    end
end
```

and then in Rust...

```rust
local f: Function<'lua> = ...;
local wrap_ready = lua_ctx.load(WRAP_READY_SRC).eval()?;
local f_wrapped: Function<'lua> = wrap_ready.call(f)?;
```

...or something along those lines.

**Comment by surajpayu** [comment]
i tried doing a eval on a file which contains below code
```
function wrap_ready(t) print(t) return t end
```

But it gives below error
```
index table     table: 0x7f62a0034e90
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversionError { from: "nil", to: "function", message: None }', src/libcore/result.rs:999
```

I am getting same issue when i define it as a string in rust

**Comment by surajpayu** [comment]
did you get a chance to look into this?

**Comment by kyren** [comment]
The reason you're getting that error is because `function wrap_ready(t) <...> end` is a statement, not an expression.

Try just `function(t) <...> end`

**Comment by Ekleog** [comment]
I've just packaged this trick as https://crates.io/crates/rlua-async ! :) (other `async` variants of regular functions coming soon, when I'll get actually used to `rlua` and understanding how it all fits together, and will notice that I'm missing some functions -- unless someone files issues for the missing functions, obviously)

That said, there is one thing that makes me sad: I haven't been able to reduce the lifetime of `RetFut` below `'static`, due to the bound on `create_function`, [here](https://github.com/Ekleog/rlua-async/blob/master/src/lib.rs#L61). Which, I think, will probably create issues when there'll be actual async code that creates things after an await point.

That being said, I haven't been able to actually hit this issue, because `Context` is not `Send`, and that is enough to prevent keeping a `Context` across an await point.

Do you have ideas on how to solve these two problems, that block compiling something like this due to `ctx` being alive across the `.await` and not being `Send`?
```rust
lua_ctx.create_async_function(|ctx, a: usize| async move {
    futures_timer::Delay::new(Duration::from_millis(50)).await;
    Ok(ctx.create_function(|ctx, b: usize| Ok(a + b)).unwrap())
})
```

**Comment by jugglerchris** [comment]
Closing as I think the original issue has been answered.
@Ekleog I'm not sure if you've solved your issue, or perhaps given up...  As you say `ctx` can't be live across await points since it's destroyed when the calling Rust code exits (e.g. after yielding).  I wonder if there could be some kind of proxy which can return a temporary `Context` when called from within an async context.  If this question is still relevant please open a new issue and we can try to figure something out!
