### ISSUE TITLE
Is f-strings' usage of debug compatible with rlua or will it cause unsafety?

### ISSUE THREAD

**Issue by AlphaModder** [amethyst/rlua#123]
Hello! Thank you for such a high-quality and comprehensive library. 

I'm interested in using [hishamhm's implementation of string interpolation](https://github.com/hishamhm/f-strings/blob/master/F.lua) in a project with `rlua`. 

This implementation depends on using the `debug.getinfo`, `debug.getlocal`, and `debug.getupvalue` functions to interpret expressions in the right environment. I've seen the big warning about `debug` in the README, so I'm wondering if this code would cause unsafety if used under `rlua`, despite not mutating anything through `debug`.

Thanks!

**Comment by kyren** [comment]
Depends on your definition of unsafety, really.  If it has no bugs, then it probably won't make correct scripts cause memory unsafety.  Even if it has no bugs, it could allow *incorrect* scripts to cause memory unsafety, but you could [almost certainly](https://github.com/kyren/rlua/issues/116) do that already without enabling debug.  Even if #116 was fixed, you could almost certainly *still* do it.

I need to update the README to make the point about the unsafety of the debug library and the safety of rlua a bit more subtle, since the safety situation around PUC-Lua is IMO pretty bleak.

**Comment by AlphaModder** [comment]
Fair enough. I'm not using this for anything vaguely security-critical, so that's good enough for me.

**Comment by jugglerchris** [comment]
Closing as answered.
