### ISSUE TITLE
How to call a lua function in a closure that would be stored in a Box<Fn()>?

### ISSUE THREAD

**Issue by slmjkdbtl** [amethyst/rlua#133]
```rust
struct Server<'a> {
	handlers: Vec<Box<Fn() + 'a>>,
}

impl<'a> Server<'a> {
	fn handle<F: Fn() + 'a>(&mut self, f: F) {
		self.handlers.push(Box::new(f));
	}
}

impl<'a> UserData for Server<'a> {
	fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
		methods.add_method_mut("handle", |ctx, serv, (f): (rlua::Function)| {
			return Ok(serv.handle(move || {
 				f.call::<_, ()>(()); // conflicting lifetime 
			}));
		});

	}

}
```
is there a way to make `f: rlua::Function` able to be called in `Server::handle`?

**Comment by kyren** [comment]
What it seems like you're trying to do is keep Lua values around outside of a context.  That's fine, you can do that, but you can't do it via a handle type like `rlua::Function`, you need something like `rlua::RegistryKey` to keep them around.  The docs for this should be better, imo.

**Comment by slmjkdbtl** [comment]
Thanks for the reply!

Do you mean something like
```rust
methods.add_method_mut("handle", |ctx, serv, (f): (Function)| {
	serv.keys.push(ctx.create_registry_value(f)?);
	return Ok(());
});
methods.add_method("exec", |ctx, serv, (f): (Function)| {
	for k in &serv.keys {
		ctx.registry_value::<Function>(k)?.call::<_, ()>(());
	}
	return Ok(());
});
```
this way works, but then I have to keep a `keys: Vec<rlua::RegistryKey>` in my struct. I guess I could make a wrapper struct to hold those keys.

**Comment by kyren** [comment]
You can either keep a `rlua::RegistryKey` inside your struct, or you could capture it in a `Box<Fn()>` like you were trying to do before, either way.  You can do anything you want with them more or less, they're Send + 'static, that's why they exist.

Just be careful since it's easy to write a memory leak with them (they're not garbage collected, even though they can be pseudo garbage collected when they're dropped).

**Comment by slmjkdbtl** [comment]
I can capture it in a `Box<Fn()>`, but I still couldn't invoke it inside of it?
```rust
methods.add_method_mut("handle", |ctx, r, (f): (Function)| {
	let key = ctx.create_registry_value(f)?;
	r.handle(move || {
		let f = ctx.registry_value::<Function>(&key); // ctx is not 'static
		f.call::<_, ()>(());
	});
});
```
I still cannot do anything and with it except storing it and invoking it somewhere else with passing a `&Context`, and I cannot have any logic of how to invoke the function inside `r.handle` and have to write all the invoking logic in the function that takes a `&Context` to invoke.

**Comment by kyren** [comment]
Sorry, I didn't mean that you could keep it in literally a  `Box<Fn()>` with no other state and no arguments and call it somehow, I just meant that you can keep `RegistryKey`s basically wherever you want.  You're correct that you'd have to have access to the Lua state somehow to actually call it.

> ```
> methods.add_method("exec", |ctx, serv, (f): (Function)| {
> 	for k in &serv.keys {
> 		ctx.registry_value::<Function>(k)?.call::<_, ()>(());
> 	}
> 	return Ok(());
> });
> ```

I assume this method is not supposed to take a `Function` argument, right?  Other than that, your example there seems fine.  I was trying to understand what you were trying to do, and I think the `Function` argument to "exec" was confusing me.

If your boxed closure really just calls `Function::call`, then keeping a Vec of boxed Fns is not really much different than a Vec of RegistryKey.  If you need to wrap each function differently somehow and it's important to keep a Vec of closures, then you could have the closures take a &Context parameter.

If you do all that though, you now have a vec of closures that take a context... and that seems awfully similar to a regular rlua callback?  I'm not really sure, but I can't help but have the suspicion that there might be an easier solution somewhere in here, but like I said I don't really fully understand the problem so I might be wrong.  There's nothing wrong with capturing a `RegistryKey` in a Rust closure, you just have to be aware of any GC implications.

**Comment by slmjkdbtl** [comment]
Thanks. Yeah the `Function` argument in the `"exec"` method is a typo, sorry that confused. 

My case is to wrap around a simple http router struct, which is like
```rust
struct Router {
	handlers: Vec<Box<Fn(&Req) -> Option<Res>>>,
}
impl Router {
	fn get<F: Fn() -> impl AsRef[u8] + 'static>(pat: &str, f: F) {
		self.handlers.push(Box::new(move |req| {
			if req.path() == pat {
				return Some(Res::new(f())); // there's some logic here to invoke this f(), and if only have a RegistryKey, I have to write all the logics to the place where f() is invoked with a &Context passed
			} else {
				return None;
			}
		}));	
	}
}
```
and the expected lua api is similar to rust's
```lua
local r = router()
r:get("/", function()
	return "yo"
end)
```
I can make all the `Box<Fn>`s take a `&Context` argument, but my goal is to keep all the lua binding stuff in a separate module and not having any of those in the base modules. I guess the best working solution right now might just be making another struct and copy&paste code:
```rust
struct LuaRouter {
	handlers: Vec<Box<Fn(&Req, &rlua::Context) -> Option<Res>>>,
}
```

**Comment by kyren** [comment]
Right I understand better now, and it does make sense that you wouldn't want `Router` to have to be aware of Lua specifically.

In that case, the best way to look at this is from the perspective of the `Box<Fn(&Req) -> Res>` request handler.  Either it will have to own its own Lua state or have an Rc to a shared Lua state, that's basically the only way it could possibly work.  I mean, regardless of what the rlua API is, it *must* keep a Lua state alive in order to work, right?  So it makes sense for it to require either owning or sharing ownership of a top-level `Lua` state.

You *can* do that though, it is sometimes perfectly sensible to share lots of `Rc<Lua>`s around, or even sometimes to keep a `Lua` in thread-local storage.  In this instance, if you're okay with that design, you could keep an `Rc<Lua>` and a `RegistryKey` in the callback and then not have to pass a `Context` as a callback parameter.  Of course, that just raises additional questions, like how do you get the `Rc<Lua>` to capture in the request handler in the first place... you can't let `Lua` own an `Rc<Lua>` to itself, because that's a memory leak!

It should be possible to provide a way for Lua to set up request handlers in such a manner that the function that Lua calls has access to an `Rc<Lua>` without Lua actually *owning* an `Rc<Lua>`.  This is the sort of thing that scoped `UserData` is sometimes useful for.

Another way of doing this which is potentially simpler is to keep the table inside Lua, so somewhere in Lua (the registry?) is a table of Lua strings -> functions, and then the request handler functions just go look up the handler functions in the registry, and in this way you don't have to work so hard to give access to an `Rc<Lua>` from a Lua callback (which is kind of a weird thing to want to do anyway), and instead the callbacks can just insert the handler function in the registry.

These sorts of issues come up a lot, it's really easy to get yourself into a confusing ownership situation when working across language boundaries.  This isn't specific to rust at all, btw, this is actually a problem I've had with most high level language binding systems... things get ugly at the boundaries between two different garbage collector systems.  It's best to try to come up with the simplest structure you can, and it's best to limit object ownership to be either host -> embedded, or embedded -> host, and *never* mix the two.

**Comment by jugglerchris** [comment]
Closing as I believe this has been answered.
