### ISSUE TITLE
clean way to distingush between a Vec and HashMap while implementing from_lua

### ISSUE THREAD

**Issue by surajprak** [amethyst/rlua#139]
My lua code is calling a rust function which takes 
enum LuaInput{
      Integer(i32),
      String(String),
       Map(HashMap<String, LuaInput),
       Array(Vec<LuaInput>),
}

How do i clearly distinguish between Array and Map while implementing from_lua for LuaInput?

**Comment by LPGhatguy** [comment]
This is a classic Lua problem, due to Lua sharing one data structure for list-like and map-like data.

One approach is to enumerate all of the keys in the table and ensure they're contiguous integers to create a Vec, else create a map. You can look at the various JSON implementations for Lua for other tricks. Some of them track how densely packed the numeric keys are to decide whether a table should encode as an array or object.

It's important to note that table keys in Lua are not limited to strings. The map case may need to handle LuaInput keys if you care about that.
